#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy 
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)   # 1 row and 5 cloumns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2D array 
arr2=np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(arr2)
print(arr2.shape)  ## 2 rows and 5 ccloumns

[[1 2 3 4 5]
 [6 7 8 9 1]]
(2, 5)


In [15]:
## convert 1D to 2D array
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])